### ISSUE TITLE
Penasaran

### ISSUE THREAD

**Issue by ekoeryanto** [o2system/o2system#1]
Ane dulu pernah bikin framework sendiri kayak gini. karena males mempelajari sampe dalem framework orang lain. terus ane sadar, tentang maintenance. nah ane penasaran, kenapa @steevenz  bikin ini framework, apa keunggulannya, apa motivasinya, kenapa harus pilih framework ini? sedangkan disana ada Laravel, Phalcon, dll.

Hatur nuhun, kang.

_urang sunda oge nu komen teh. ieu_

**Comment by steevenz** [comment]
Halo @ekoeryanto.. pertama-tama terima kasih untuk perhatiannya kepada framework o2system. Saya akan coba jelaskan secara umum, karena sebetulnya banyak yang harus diutarakan alasan, keunggulan dan lain sebagainya. Motivasi saya sederhana, saya ingin mengajak para programmer Indonesia untuk mulai berkontribusi ke dunia open-source, bukan hanya bisa saja menjadi pengguna semata. Sama pertanyaan yang harusnya kita ajukan kepada Taylor Otwel.. mengapa harus membuat Laravel tidak menggunakan CodeIgniter, Phalcon dan lain-lain. Patut kita sadari bahwa kehadiran open-source membuat kita dapat mencari membantu banyak orang dapat bekerja lebih baik, lebih cepat, dan dapat menjadi penghidupan. Ini pula yang menjadi motivasi saya kedua.. yaitu ingin menjadi berkah bagi banyak orang dan membantu banyak orang.

Bercerita mengenai keunggulan banyak sekali keunggulan yang tidak dapat saya utarakan satu-persatu, namun untuk menjawab pertanyaan diatas mengenai keberadaan O2System Framework sebagai pilihan baru selain Laravel, Phalcon, dan lain sebagainya. Ketika berbicara mengenai sesuatu yang sudah ada, kita memang harus berusaha untuk tidak "re-invent the whell" memang, oleh karena itu ketika saya mulai membangun kembali O2System Framework tahun lalu saya mencoba membuat sesuatu yang baru, dimulai dari tidak bergantung terlalu banyak kepada libraries lain supaya terlihat originalitas konsepnya yang selanjutnya bisa dibaca dibeberapa documentation yang sudah saya coba tuliskan di [GitBook](https://o2system.gitbooks.io/framework-id/content/).

Target pertama dari O2System Framework sendiri adalah menjadi sebuah framework generasi masa depan yang dapat membantu mempercepat pembuatan project (Rapid Application Development). Sebagai contoh.. dalam O2System Framework sudah terdapat O2System UI.. yang tentunya dapat mempercepat proses pembuatan website, landing, mock-up, dan admin interface. Sebagai informasi saat ini O2System Framework sudah menyiapkan beberapa pilihan boilerplate: 
1. O2System Basic (Boilerplate Project base bagi yang senang membangun from scratch)
2. O2System Webrestful (Boilerplate Project bagi yang ingin membangun aplikasi restful)
3. O2System Webcli (Boilerplate Project bagi yang ingin membangun aplikasi CLI untuk cron dan lain sebagainya)
akan menyusul 2 lagi yang akan diluncurkan.

Target kedua dari O2System Framework adalah mudah melakukan scaling, karena sudah mensupport sistem Modular HMVCP, dan mudah untuk menambah library karena sudah didukung oleh Composer dan masih banyak lagi..

Seperti saya utarakan diatas saya tidak bisa bercerita terlalu banyak mengenai keunggulannya.. tapi harus dicoba dan dirasakan sendiri.. karena setiap framework memiliki ciri khas dan keunggulan masing-masing. O2System Framework dibuat berdasarkan riset dari seluruh framework yang ada di PHP, Project CMS Opensource seperti Joomla, Wordpress, dan beberapa konsep dari programming lain. Atas dasar ini tentunya berharap dapat menutupi kekurangan framework lain dan dapat menggabungkan keunggulan-keunggulan framework-framework lain kedalam satu framework.

Mengenai maintenance ya betul.. saya bukan Superman ^_^ yang bisa maintenance semua.. tapi saya berusaha sebaik mungkin untuk melakukannya.. dan tentunya saya mengajak semua pihak termasuk mas @ekoeryanto sendiri untuk ayo berkontribusi di framework ini..

Mohon maaf apabila ada kurang kata dari saya.. maafkan apabila ada yang kurang berkenan.. saya harap bisa cukup memberi penjelasan... jika ingin ngobrol lebih lanjut.. please feel free buat add saya di LINE dengan id steevenz.. atau mungkin mau hang-out bareng.. salam kenal ya mas @ekoeryanto .. semoga kita bisa berkenalan lebih lanjut.. terima kasih banyak buat comment nya..

**Comment by ekoeryanto** [comment]
Halo, @steevenz. Terimakasih karena telah sudi menulis sedemikian panjang.
maaf saya baru bisa membalas karena ada kesalahan setting notifikasi saat akun saya yang lama saya jadikan sebuah organisasi, @nueko. 
> tidak bergantung terlalu banyak kepada libraries lain...

itu juga salah satu saya dulu membuat framework sendiri untuk dipakai pribadi dan rekan2

> ingin menjadi berkah bagi banyak orang dan membantu banyak orang.

karena kalimat diatas saya mulai tertarik. Saya akan mencoba membantu sebisa saya. mungkin ga bisa terlalu karena 1 tahun terakhir ini saya jarang bergelut dengan PHP bahkan saya belum mencicipi laravel 5.6 😄 , tapi di client side, Angular, React, Vue, NodeJS dan cloud computing.

Oh ya, Semangat!
Saya mendukung @steevenz !

**Comment by steevenz** [comment]
Wah terima kasih banyak ya.. buat dukungannya.. kalo ada meetup ikutan ya.. semoga kita bs berkenalan lebih jauh disana nanti..

**Comment by PurwadiPw** [comment]
Apakah akan tetap konsisten dan fokus dengan O2System Framework yang telah di bangun ini ?

**Comment by steevenz** [comment]
> Apakah akan tetap konsisten dan fokus dengan O2System Framework yang telah di bangun ini ?

Halo juga @PurwadiPw tentunya pasti focus.. bahkan akan ada kejutan-kejutan menarik di tahun depan.. ikutin terus ya perkembangannya... terima kasih

**Comment by ghost** [comment]
saya bangga o2system framework karya indonesia
