### ISSUE TITLE
PHP 7+ for Performance

### ISSUE THREAD

**Issue by ekoeryanto** [o2system/o2system#2]
Halo, saya tahu. hal ini akan menjadi sebuah pekerjaan rumah yang sangat banyak.
Tapi akan lebih baik jika hal ini direncanakan.

Terimakasih.

>Mohon maaf penggunaan bahasanya, sedikit aneh nulis di github pake bahasa indonesia ☮️ 🇮🇩

**Comment by steevenz** [comment]
Saat ini untuk performance menggunakan PHP 7+ sangat baik.. sedangkan untuk versi 5.6 sudah tidak disupport.. kedepannya akan terus dicoding diatas PHP7+
